nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: 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

npmScopes:
  shsusac:
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.1.1.cjs
