name: Create release on merge
"on":
  push:
    branches:
      - main
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
      - "README.md"
      - "LICENSE.md"
jobs:
  build_release:
    permissions:
      packages: read
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          token: ${{ secrets.PAT_GITHUB }}

      - name: Pull Tags
        run: git fetch --prune --tags

      - run: npm install -g yarn
        if: ${{ env.ACT }}

      - name: Setup Node and Cached Dependencies
        if: ${{ !env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --immutable --check-cache
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: yarn run test#ci

      - uses: actions/upload-artifact@v2
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: junit.xml

## For some reason, this doesn't work inline, so it's disabled
#      - name: Test Report
#        uses: dorny/test-reporter@v1
#        if: success() || failure()    # run this step even if previous step failed
#        with:
#          artifact: test-results            # artifact name
#          name: JEST Tests                  # Name of the check run which will be created
#          path: '*.xml'                     # Path to test results (inside artifact .zip)
#          reporter: jest-junit              # Format of test results

      - name: Build Semantic Release
        if: ${{ !env.ACT }}
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
